### ISSUE TITLE
Security BUG!!!!!

### ISSUE THREAD

**Issue by levozavr** [robot-lab/projectsfair#13]
**Describe the bug**
**I can delete a project from your site http://urazoff.pythonanywhere.com/**

**To Reproduce**
1. Go to http://urazoff.pythonanywhere.com/projects/4/delete/
or http://urazoff.pythonanywhere.com/projects/3/delete/
2. Click on button named "Yes, delete"
3. See what project dissaper from main page

**Expected behavior**
AN authorization before to get this page if you are a creater of project or redirect to other page

**Screenshots**
![image](https://user-images.githubusercontent.com/30433199/44481235-f5b87800-a64d-11e8-8115-7e9c25405a88.png)

**Desktop (please complete the following information):**
 - OS: Debian-9.4
 - Browser chrome

**Additional context**
Be careful with security, @urazoff , @nikita03565

**Comment by urazoff** [comment]
We published the site not for third-party testing so far. The project is not yet ready and we know that it has a lot of bugs and flaws. But thanks. We will ask you to test our project in near future:)

**Comment by nikita03565** [comment]
b4c00b8737acbf2f2bbf5d593c1a2f871a0e794e
