### ISSUE TITLE
Минимальный жизнеспособный продукт.

### ISSUE THREAD

**Issue by nikita03565** [robot-lab/projectsfair#47]
# Idea proposal

## В чём заключается идея
Создать минимальный жизнеспособный продукт для выхода в релиз и получения обратной связи.

## Возможное решение
- Переработать имеющуюся версию продукта;
- Добавить минимальный функционал;
- Разработать систему для постоянной поставки обновлений.

## Дополнительный контекст или ссылки на связанные с данной задачей issues

[Ссылка](https://drive.google.com/drive/u/0/folders/1VRjUOGeYRQsNAngFMVllssyAo7IzHr_r) на папку с аналитикой.

**Comment by ptrdiff** [comment]
Для перехода на новый процесс разработки больше нет необходимости issue такого типа.
