### ISSUE TITLE
Привести проект в порядок

### ISSUE THREAD

**Issue by nikita03565** [robot-lab/projectsfair#48]
# Code maintenance request

## Опишите проблему, которая приводит к необходимости этих изменений
Внутреннее устройство текущего репозитория проекта не удовлетворяет выбранной модели разработки и затрудняет реализацию новых идей.

## Опишите, какие изменения Вы считаете необходимыми
- Разобраться с кодом, оставшимся с августа;
- Перейти на github flow;
- Дополнить описание проекта;
- Слить и удалить ненужные ветки;
- Создать модель архитектуры системы;
- Дополнить readme и wiki.

## Дополнительные материалы
#47

**Comment by ptrdiff** [comment]
Частично была выполнена, дальнейшие изменения будут обсуждаться командой.
