### ISSUE TITLE
Обновленный минимальный профиль проекта

### ISSUE THREAD

**Issue by nikita03565** [robot-lab/projectsfair#50]
# Feature request

## Почему Вы заинтересованы в данном функционале

Необходим профиль проекта для первого запуска в релиз.
На основании idea #47 

## Функционал, который Вы хотите

Реализовать оговоренную минимальную структуру профиля.

## Как Вы будете использовать этот функционал

Будет предоставлен доступ к системе, где пользователи смогут заполнять уже обновленный профиль проекта, который обеспечит выполнение базовых сценариев.

## Кому будет интересен данный функционал

Новым пользователям и самой команде разработки.

## Дополнительный контекст или ссылки на связанные с данной задачей issues

[Ссылка](https://docs.google.com/document/d/1oeohHlzfjGhO0pvQmX24E7yO42DfbFcLnrCgejVBtHk/edit?usp=sharing) на документ с описанной структурой проекта.

**Comment by ptrdiff** [comment]
При измененном процессе работы данная issue не отражает необходимые действия для работы.
