### ISSUE TITLE
Реализовать поиск по тегам

### ISSUE THREAD

**Issue by nikita03565** [robot-lab/projectsfair#52]
# Feature request

## Почему Вы заинтересованы в данном функционале
Без системы поиска пользователям будет очень сложно-почти-невозможно найти интересующие их проекты или подобрать исполнителей.
На основании idea  #47.

## Функционал, который Вы хотите
Для выбора подходящих проектов и исполнителей первым делом необходим поиск по тегам.

## Как Вы будете использовать этот функционал
Будет предоставлен доступ к системе, где пользователи смогут выставлять фильтры по тегам.

## Кому будет интересен данный функционал
Новым пользователям и самой команде разработки.

## Дополнительный контекст или ссылки на связанные с данной задачей issues
[Ссылка](https://docs.google.com/document/d/17kUCMcbSoU2AMM759TAlmjzblDm43xjnXY40KEqMeTc/edit) на документ с аналитикой.

**Comment by ptrdiff** [comment]
При измененном процессе работы данная issue не отражает необходимые действия для работы.
