### ISSUE TITLE
Добавить систему непрерывных обновлений

### ISSUE THREAD

**Issue by nikita03565** [robot-lab/projectsfair#53]
# Code maintenance request

## Опишите проблему, которая приводит к необходимости этих изменений
Продукт должен иметь возможность обновления с минимальным временем прерывания его работы и без потерь данных пользователей. На основании idea #47.

## Опишите, какие изменения Вы считаете необходимыми
Внедрить систему CI/CD.

**Comment by ptrdiff** [comment]
Сейчас имеется автоматический деплой на несколько платформ при обновлении кода проекта.
