### ISSUE TITLE
Создание базы под новые поля

### ISSUE THREAD

**Issue by OlegMoiseev** [robot-lab/projectsfair#65]
# Task request

## Цель задачи
Создать базу данных в соответствии с новыми профилями пользователя и проекта.
На основании #51.

## Решение задачи
- Спроектировать архитектуру БД;
- Сменить БД в проекте с SQLite на PostgreSQL;
- Настроить взаимодействие системы с новой базой.

**Comment by ptrdiff** [comment]
Уже есть подобная задача.
