### ISSUE TITLE
Не добавляется руководитель проекта при создании проекта

### ISSUE THREAD

**Issue by OlegMoiseev** [robot-lab/projectsfair#75]
# Bug report

## Описание ошибки

При создании проекта не добавляется руководитель в поле руководителя.

## Воспроизводение ошибки

Действия по воспроизведению поведения:

1. Создать проект;
2. Зайти в "Посмотреть непроверенные проекты" с аккаунта модератора;
3. Зайти в созданный проект;
4. Увидеть пустое поле с именем руководителя.

## Ожидаемое поведение

В поле имени руководителя выводится имя руководителя.

## Рабочее окружение (пожалуйста, заполните следующую информацию)

- ОС: Ubuntu 18.04
- Браузер: Chrome

**Comment by nikita03565** [comment]
56c9aae
